import Head from 'next/head';
import About from '../components/About';
import Contact from '../components/Contact';
import Main from '../components/Main';
import Projects from '../components/Projects';
import Tools from '../components/Tools';

export default function Home() {
  return (
    <div className="bg-[#e4e0da]">
      <Head>
        <title>Kgio | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Main/>
    <About/>
    <Tools/>
    <Projects/>
    <Contact/>
    </div>
  )
}
